# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 79206cfc16175b6446220b546e712885ef647a36031daea3f338bdf25a6b76b16240ba4abda80eb7dbdd43adb0587809cbb146df00a2f394a5d8c82cdb92699c

test:
  secret_key_base: 91ef3f5e76026e83d90b05c05b32c6f25fd12a801cd039cfd781208f5db2018e6cbfa3b659564be8f85e83d232f19526a85f3aac3876681e100aa8a77232e9a7

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
